import { Product } from './entity'

export const productListMock: Product[] = [
  {
    productId: '10035',
    displayName: 'Solgar, пиколинат цинка, 100 таблеток',
    url: 'https://ru.iherb.com/pr/Solgar-Zinc-Picolinate-100-Tablets/10035',
    partNumber: 'SOL-03725',
    listPrice: '₽637.80',
    discountPrice: '₽637.80',
    tag: null,
    isOutOfStock: false,
    hidePrice: false,
    isDiscontinued: false,
    isNotAvailable: false,
    showDiscount: false,
    rating: 4.8,
    ratingCount: 8830,
    ratingUrl:
      'https://ru.iherb.com/pr/Solgar-Zinc-Picolinate-100-Tablets/10035#product-detail-reviews',
    reviewUrl:
      'https://ru.iherb.com/r/Solgar-Zinc-Picolinate-100-Tablets/10035',
    isShippingSaver: false,
    isFeaturedBrand: false,
    productFlags: null,
    showGroupMessage: false,
    isProductCompared: false,
    isSeasonallyUnavailable: false,
    discountPercentage: null,
    salesDiscountPercentage: 0.0,
    brandCode: 'SOL',
    primaryImageIndex: 59,
    specialDealInfo: null,
    hasRating: true,
    hasTag: false,
    currencySymbol: '₽',
    isCurrencySymbolOnLeft: true,
    discountPriceValue: '637.80',
    discountMessage: null,
    isComingSoon: false,
    discountType: 0,
    ratingStarsMap: [1.0, 1.0, 1.0, 1.0, 0.75],
  },
  {
    productId: '68678',
    displayName:
      'Nutiva, Органическое кокосовое масло, с ароматом сливочного масла, 414 мл (14 жидк. унций)',
    url: 'https://ru.iherb.com/pr/Nutiva-Organic-Coconut-Oil-Butter-Flavor-14-fl-oz-414-ml/68678',
    partNumber: 'NUT-10676',
    listPrice: '₽501.08',
    discountPrice: '₽501.08',
    tag: null,
    isOutOfStock: false,
    hidePrice: false,
    isDiscontinued: false,
    isNotAvailable: false,
    showDiscount: false,
    rating: 4.7,
    ratingCount: 8563,
    ratingUrl:
      'https://ru.iherb.com/pr/Nutiva-Organic-Coconut-Oil-Butter-Flavor-14-fl-oz-414-ml/68678#product-detail-reviews',
    reviewUrl:
      'https://ru.iherb.com/r/Nutiva-Organic-Coconut-Oil-Butter-Flavor-14-fl-oz-414-ml/68678',
    isShippingSaver: false,
    isFeaturedBrand: false,
    productFlags: null,
    showGroupMessage: false,
    isProductCompared: false,
    isSeasonallyUnavailable: false,
    discountPercentage: null,
    salesDiscountPercentage: 0.0,
    brandCode: 'NUT',
    primaryImageIndex: 3,
    specialDealInfo: null,
    hasRating: true,
    hasTag: false,
    currencySymbol: '₽',
    isCurrencySymbolOnLeft: true,
    discountPriceValue: '501.08',
    discountMessage: null,
    isComingSoon: false,
    discountType: 0,
    ratingStarsMap: [1.0, 1.0, 1.0, 1.0, 0.75],
  },
  {
    productId: '40504',
    displayName:
      "Nature's Plus, Source of Life Animal Parade Gold, добавка для детей с мультивитаминами и минералами, ассорти из натуральных вкусов, 120 таблеток в форме животных",
    url: 'https://ru.iherb.com/pr/Nature-s-Plus-Source-of-Life-Animal-Parade-Gold-Children-s-Chewable-Multi-Vitamin-Mineral-Supplement-Natural-Assorted-Flavors-120-Animal-Shaped-Tablets/40504',
    partNumber: 'NAP-29928',
    listPrice: '₽1,427.95',
    discountPrice: '₽1,427.95',
    tag: null,
    isOutOfStock: false,
    hidePrice: false,
    isDiscontinued: false,
    isNotAvailable: false,
    showDiscount: false,
    rating: 4.7,
    ratingCount: 13456,
    ratingUrl:
      'https://ru.iherb.com/pr/Nature-s-Plus-Source-of-Life-Animal-Parade-Gold-Children-s-Chewable-Multi-Vitamin-Mineral-Supplement-Natural-Assorted-Flavors-120-Animal-Shaped-Tablets/40504#product-detail-reviews',
    reviewUrl:
      'https://ru.iherb.com/r/Nature-s-Plus-Source-of-Life-Animal-Parade-Gold-Children-s-Chewable-Multi-Vitamin-Mineral-Supplement-Natural-Assorted-Flavors-120-Animal-Shaped-Tablets/40504',
    isShippingSaver: false,
    isFeaturedBrand: false,
    productFlags: null,
    showGroupMessage: false,
    isProductCompared: false,
    isSeasonallyUnavailable: false,
    discountPercentage: null,
    salesDiscountPercentage: 0.0,
    brandCode: 'NAP',
    primaryImageIndex: 28,
    specialDealInfo: null,
    hasRating: true,
    hasTag: false,
    currencySymbol: '₽',
    isCurrencySymbolOnLeft: true,
    discountPriceValue: '1427.95',
    discountMessage: null,
    isComingSoon: false,
    discountType: 0,
    ratingStarsMap: [1.0, 1.0, 1.0, 1.0, 0.75],
  },
  {
    productId: '7511',
    displayName:
      "Nature's Plus, Animal Parade, добавка для детей с мультивитаминами и минералами, ассорти из натуральных вкусов, 180 жевательных таблеток в форме животных",
    url: 'https://ru.iherb.com/pr/Nature-s-Plus-Source-of-Life-Animal-Parade-Children-s-Chewable-Multi-Vitamin-and-Mineral-Supplement-Natural-Assorted-Flavors-180-Animal-Shaped-Tablets/7511',
    partNumber: 'NAP-29982',
    listPrice: '₽1,427.95',
    discountPrice: '₽1,427.95',
    tag: null,
    isOutOfStock: false,
    hidePrice: false,
    isDiscontinued: false,
    isNotAvailable: false,
    showDiscount: false,
    rating: 4.7,
    ratingCount: 8259,
    ratingUrl:
      'https://ru.iherb.com/pr/Nature-s-Plus-Source-of-Life-Animal-Parade-Children-s-Chewable-Multi-Vitamin-and-Mineral-Supplement-Natural-Assorted-Flavors-180-Animal-Shaped-Tablets/7511#product-detail-reviews',
    reviewUrl:
      'https://ru.iherb.com/r/Nature-s-Plus-Source-of-Life-Animal-Parade-Children-s-Chewable-Multi-Vitamin-and-Mineral-Supplement-Natural-Assorted-Flavors-180-Animal-Shaped-Tablets/7511',
    isShippingSaver: false,
    isFeaturedBrand: false,
    productFlags: null,
    showGroupMessage: false,
    isProductCompared: false,
    isSeasonallyUnavailable: false,
    discountPercentage: null,
    salesDiscountPercentage: 0.0,
    brandCode: 'NAP',
    primaryImageIndex: 44,
    specialDealInfo: null,
    hasRating: true,
    hasTag: false,
    currencySymbol: '₽',
    isCurrencySymbolOnLeft: true,
    discountPriceValue: '1427.95',
    discountMessage: null,
    isComingSoon: false,
    discountType: 0,
    ratingStarsMap: [1.0, 1.0, 1.0, 1.0, 0.75],
  },
  {
    productId: '12650',
    displayName:
      'Solgar, комплекс витаминов B с витамином C, формула для борьбы со стрессом, 250 таблеток',
    url: 'https://ru.iherb.com/pr/Solgar-B-Complex-with-Vitamin-C-Stress-Formula-250-Tablets/12650',
    partNumber: 'SOL-00201',
    listPrice: '₽1,682.02',
    discountPrice: '₽1,682.02',
    tag: null,
    isOutOfStock: false,
    hidePrice: false,
    isDiscontinued: false,
    isNotAvailable: false,
    showDiscount: false,
    rating: 4.6,
    ratingCount: 2220,
    ratingUrl:
      'https://ru.iherb.com/pr/Solgar-B-Complex-with-Vitamin-C-Stress-Formula-250-Tablets/12650#product-detail-reviews',
    reviewUrl:
      'https://ru.iherb.com/r/Solgar-B-Complex-with-Vitamin-C-Stress-Formula-250-Tablets/12650',
    isShippingSaver: false,
    isFeaturedBrand: false,
    productFlags: null,
    showGroupMessage: false,
    isProductCompared: false,
    isSeasonallyUnavailable: false,
    discountPercentage: null,
    salesDiscountPercentage: 0.0,
    brandCode: 'SOL',
    primaryImageIndex: 53,
    specialDealInfo: null,
    hasRating: true,
    hasTag: false,
    currencySymbol: '₽',
    isCurrencySymbolOnLeft: true,
    discountPriceValue: '1682.02',
    discountMessage: null,
    isComingSoon: false,
    discountType: 0,
    ratingStarsMap: [1.0, 1.0, 1.0, 1.0, 0.5],
  },
  {
    productId: '69333',
    displayName: 'Jarrow Formulas, метил B12 и метилфолат, лимон, 100 пастилок',
    url: 'https://ru.iherb.com/pr/Jarrow-Formulas-Methyl-B-12-Methyl-Folate-Lemon-100-Lozenges/69333',
    partNumber: 'JRW-18018',
    listPrice: '₽902.24',
    discountPrice: '₽902.24',
    tag: null,
    isOutOfStock: false,
    hidePrice: false,
    isDiscontinued: false,
    isNotAvailable: false,
    showDiscount: false,
    rating: 4.8,
    ratingCount: 4462,
    ratingUrl:
      'https://ru.iherb.com/pr/Jarrow-Formulas-Methyl-B-12-Methyl-Folate-Lemon-100-Lozenges/69333#product-detail-reviews',
    reviewUrl:
      'https://ru.iherb.com/r/Jarrow-Formulas-Methyl-B-12-Methyl-Folate-Lemon-100-Lozenges/69333',
    isShippingSaver: false,
    isFeaturedBrand: false,
    productFlags: null,
    showGroupMessage: false,
    isProductCompared: false,
    isSeasonallyUnavailable: false,
    discountPercentage: null,
    salesDiscountPercentage: 0.0,
    brandCode: 'JRW',
    primaryImageIndex: 24,
    specialDealInfo: null,
    hasRating: true,
    hasTag: false,
    currencySymbol: '₽',
    isCurrencySymbolOnLeft: true,
    discountPriceValue: '902.24',
    discountMessage: null,
    isComingSoon: false,
    discountType: 0,
    ratingStarsMap: [1.0, 1.0, 1.0, 1.0, 0.75],
  },
  {
    productId: '82466',
    displayName:
      'Country Life, Vitamin D3, High Potency, 250 mcg (10,000 IU), 200 Softgels',
    url: 'https://ru.iherb.com/pr/Country-Life-High-Potency-Vitamin-D3-250-mcg-10-000-IU-200-Softgels/82466',
    partNumber: 'CLF-05816',
    listPrice: '₽1,576.85',
    discountPrice: '₽1,576.85',
    tag: null,
    isOutOfStock: false,
    hidePrice: false,
    isDiscontinued: false,
    isNotAvailable: false,
    showDiscount: false,
    rating: 4.9,
    ratingCount: 463,
    ratingUrl:
      'https://ru.iherb.com/pr/Country-Life-High-Potency-Vitamin-D3-250-mcg-10-000-IU-200-Softgels/82466#product-detail-reviews',
    reviewUrl:
      'https://ru.iherb.com/r/Country-Life-High-Potency-Vitamin-D3-250-mcg-10-000-IU-200-Softgels/82466',
    isShippingSaver: false,
    isFeaturedBrand: false,
    productFlags: null,
    showGroupMessage: false,
    isProductCompared: false,
    isSeasonallyUnavailable: false,
    discountPercentage: null,
    salesDiscountPercentage: 0.0,
    brandCode: 'CLF',
    primaryImageIndex: 19,
    specialDealInfo: null,
    hasRating: true,
    hasTag: false,
    currencySymbol: '₽',
    isCurrencySymbolOnLeft: true,
    discountPriceValue: '1576.85',
    discountMessage: null,
    isComingSoon: false,
    discountType: 0,
    ratingStarsMap: [1.0, 1.0, 1.0, 1.0, 1.0],
  },
  {
    productId: '40593',
    displayName:
      "Doctor's Best, альфа-липоевая кислота, 300 мг, 180 вегетарианских капсул",
    url: 'https://ru.iherb.com/pr/Doctor-s-Best-Alpha-Lipoic-Acid-300-300-mg-180-Veggie-Caps/40593',
    partNumber: 'DRB-00277',
    listPrice: '₽1,556.70',
    discountPrice: '₽1,556.70',
    tag: null,
    isOutOfStock: false,
    hidePrice: false,
    isDiscontinued: false,
    isNotAvailable: false,
    showDiscount: false,
    rating: 4.7,
    ratingCount: 1237,
    ratingUrl:
      'https://ru.iherb.com/pr/Doctor-s-Best-Alpha-Lipoic-Acid-300-300-mg-180-Veggie-Caps/40593#product-detail-reviews',
    reviewUrl:
      'https://ru.iherb.com/r/Doctor-s-Best-Alpha-Lipoic-Acid-300-300-mg-180-Veggie-Caps/40593',
    isShippingSaver: false,
    isFeaturedBrand: false,
    productFlags: null,
    showGroupMessage: false,
    isProductCompared: false,
    isSeasonallyUnavailable: false,
    discountPercentage: null,
    salesDiscountPercentage: 0.0,
    brandCode: 'DRB',
    primaryImageIndex: 55,
    specialDealInfo: null,
    hasRating: true,
    hasTag: false,
    currencySymbol: '₽',
    isCurrencySymbolOnLeft: true,
    discountPriceValue: '1556.70',
    discountMessage: null,
    isComingSoon: false,
    discountType: 0,
    ratingStarsMap: [1.0, 1.0, 1.0, 1.0, 0.75],
  },
  {
    productId: '2475',
    displayName:
      "Doctor's Best, альфа-липоевая кислота, 600 мг, 60 вегетарианских капсул",
    url: 'https://ru.iherb.com/pr/Doctor-s-Best-Alpha-Lipoic-Acid-600-mg-60-Veggie-Caps/2475',
    partNumber: 'DRB-00133',
    listPrice: '₽925.94',
    discountPrice: '₽925.94',
    tag: null,
    isOutOfStock: false,
    hidePrice: false,
    isDiscontinued: false,
    isNotAvailable: false,
    showDiscount: false,
    rating: 4.7,
    ratingCount: 5258,
    ratingUrl:
      'https://ru.iherb.com/pr/Doctor-s-Best-Alpha-Lipoic-Acid-600-mg-60-Veggie-Caps/2475#product-detail-reviews',
    reviewUrl:
      'https://ru.iherb.com/r/Doctor-s-Best-Alpha-Lipoic-Acid-600-mg-60-Veggie-Caps/2475',
    isShippingSaver: false,
    isFeaturedBrand: false,
    productFlags: null,
    showGroupMessage: false,
    isProductCompared: false,
    isSeasonallyUnavailable: false,
    discountPercentage: null,
    salesDiscountPercentage: 0.0,
    brandCode: 'DRB',
    primaryImageIndex: 91,
    specialDealInfo: null,
    hasRating: true,
    hasTag: false,
    currencySymbol: '₽',
    isCurrencySymbolOnLeft: true,
    discountPriceValue: '925.94',
    discountMessage: null,
    isComingSoon: false,
    discountType: 0,
    ratingStarsMap: [1.0, 1.0, 1.0, 1.0, 0.75],
  },
  {
    productId: '63434',
    displayName:
      'Solgar, U-Cubes, кальций с витамином D3 для детей, вкус розового лимонада, голубики и клубники, 120 жевательных мармеладок',
    url: 'https://ru.iherb.com/pr/Solgar-U-Cubes-Children-s-Calcium-With-D3-Pink-Lemonade-Blueberry-Strawberry-120-Gummies/63434',
    partNumber: 'SOL-57600',
    listPrice: '₽1,159.91',
    discountPrice: '₽1,159.91',
    tag: null,
    isOutOfStock: false,
    hidePrice: false,
    isDiscontinued: false,
    isNotAvailable: false,
    showDiscount: false,
    rating: 4.7,
    ratingCount: 3221,
    ratingUrl:
      'https://ru.iherb.com/pr/Solgar-U-Cubes-Children-s-Calcium-With-D3-Pink-Lemonade-Blueberry-Strawberry-120-Gummies/63434#product-detail-reviews',
    reviewUrl:
      'https://ru.iherb.com/r/Solgar-U-Cubes-Children-s-Calcium-With-D3-Pink-Lemonade-Blueberry-Strawberry-120-Gummies/63434',
    isShippingSaver: false,
    isFeaturedBrand: false,
    productFlags: null,
    showGroupMessage: false,
    isProductCompared: false,
    isSeasonallyUnavailable: false,
    discountPercentage: null,
    salesDiscountPercentage: 0.0,
    brandCode: 'SOL',
    primaryImageIndex: 23,
    specialDealInfo: null,
    hasRating: true,
    hasTag: false,
    currencySymbol: '₽',
    isCurrencySymbolOnLeft: true,
    discountPriceValue: '1159.91',
    discountMessage: null,
    isComingSoon: false,
    discountType: 0,
    ratingStarsMap: [1.0, 1.0, 1.0, 1.0, 0.75],
  },
  {
    productId: '85353',
    displayName:
      'SmartyPants, комплекс мультивитаминов и омега 3 для малышей, 90 жевательных конфет',
    url: 'https://ru.iherb.com/pr/SmartyPants-Toddler-Complete-Multi-and-Omega-3s-90-Gummies/85353',
    partNumber: 'SMA-02112',
    listPrice: '₽1,423.59',
    discountPrice: '₽1,423.59',
    tag: null,
    isOutOfStock: false,
    hidePrice: false,
    isDiscontinued: false,
    isNotAvailable: false,
    showDiscount: false,
    rating: 4.8,
    ratingCount: 666,
    ratingUrl:
      'https://ru.iherb.com/pr/SmartyPants-Toddler-Complete-Multi-and-Omega-3s-90-Gummies/85353#product-detail-reviews',
    reviewUrl:
      'https://ru.iherb.com/r/SmartyPants-Toddler-Complete-Multi-and-Omega-3s-90-Gummies/85353',
    isShippingSaver: false,
    isFeaturedBrand: false,
    productFlags: null,
    showGroupMessage: false,
    isProductCompared: false,
    isSeasonallyUnavailable: false,
    discountPercentage: null,
    salesDiscountPercentage: 0.0,
    brandCode: 'SMA',
    primaryImageIndex: 0,
    specialDealInfo: null,
    hasRating: true,
    hasTag: false,
    currencySymbol: '₽',
    isCurrencySymbolOnLeft: true,
    discountPriceValue: '1423.59',
    discountMessage: null,
    isComingSoon: false,
    discountType: 0,
    ratingStarsMap: [1.0, 1.0, 1.0, 1.0, 0.75],
  },
  {
    productId: '7531',
    displayName:
      "Nature's Plus, Source of Life, Animal Parade, кальций, жевательная добавка для детей, со вкусом натурального ванильного мороженого, 90 таблеток в форме животных",
    url: 'https://ru.iherb.com/pr/Nature-s-Plus-Source-of-Life-Animal-Parade-Calcium-Children-s-Chewable-Supplement-Natural-Vanilla-Sundae-Flavor-90-Animal-Shaped-Tablets/7531',
    partNumber: 'NAP-29996',
    listPrice: '₽617.97',
    discountPrice: '₽617.97',
    tag: null,
    isOutOfStock: false,
    hidePrice: false,
    isDiscontinued: false,
    isNotAvailable: false,
    showDiscount: false,
    rating: 4.8,
    ratingCount: 14330,
    ratingUrl:
      'https://ru.iherb.com/pr/Nature-s-Plus-Source-of-Life-Animal-Parade-Calcium-Children-s-Chewable-Supplement-Natural-Vanilla-Sundae-Flavor-90-Animal-Shaped-Tablets/7531#product-detail-reviews',
    reviewUrl:
      'https://ru.iherb.com/r/Nature-s-Plus-Source-of-Life-Animal-Parade-Calcium-Children-s-Chewable-Supplement-Natural-Vanilla-Sundae-Flavor-90-Animal-Shaped-Tablets/7531',
    isShippingSaver: false,
    isFeaturedBrand: false,
    productFlags: null,
    showGroupMessage: false,
    isProductCompared: false,
    isSeasonallyUnavailable: false,
    discountPercentage: null,
    salesDiscountPercentage: 0.0,
    brandCode: 'NAP',
    primaryImageIndex: 20,
    specialDealInfo: null,
    hasRating: true,
    hasTag: false,
    currencySymbol: '₽',
    isCurrencySymbolOnLeft: true,
    discountPriceValue: '617.97',
    discountMessage: null,
    isComingSoon: false,
    discountType: 0,
    ratingStarsMap: [1.0, 1.0, 1.0, 1.0, 0.75],
  },
  {
    productId: '30740',
    displayName:
      'Frontier Natural Products, резанная и просеянная кора муравьиного дерева, 453 г (16 унций)',
    url: 'https://ru.iherb.com/pr/Frontier-Natural-Products-Cut-Sifted-Pau-d-Arco-Bark-16-oz-453-g/30740',
    partNumber: 'FRO-00702',
    listPrice: '₽654.33',
    discountPrice: '₽654.33',
    tag: null,
    isOutOfStock: false,
    hidePrice: false,
    isDiscontinued: false,
    isNotAvailable: false,
    showDiscount: false,
    rating: 4.7,
    ratingCount: 874,
    ratingUrl:
      'https://ru.iherb.com/pr/Frontier-Natural-Products-Cut-Sifted-Pau-d-Arco-Bark-16-oz-453-g/30740#product-detail-reviews',
    reviewUrl:
      'https://ru.iherb.com/r/Frontier-Natural-Products-Cut-Sifted-Pau-d-Arco-Bark-16-oz-453-g/30740',
    isShippingSaver: false,
    isFeaturedBrand: false,
    productFlags: null,
    showGroupMessage: false,
    isProductCompared: false,
    isSeasonallyUnavailable: false,
    discountPercentage: null,
    salesDiscountPercentage: 0.0,
    brandCode: 'FRO',
    primaryImageIndex: 4,
    specialDealInfo: null,
    hasRating: true,
    hasTag: false,
    currencySymbol: '₽',
    isCurrencySymbolOnLeft: true,
    discountPriceValue: '654.33',
    discountMessage: null,
    isComingSoon: false,
    discountType: 0,
    ratingStarsMap: [1.0, 1.0, 1.0, 1.0, 0.75],
  },
  {
    productId: '91050',
    displayName: 'Kirkman Labs, Biofilm Defense, 60 капсул',
    url: 'https://ru.iherb.com/pr/Kirkman-Labs-Biofilm-Defense-60-Capsules/91050',
    partNumber: 'KIM-02495',
    listPrice: '₽3,894.41',
    discountPrice: '₽3,894.41',
    tag: null,
    isOutOfStock: false,
    hidePrice: false,
    isDiscontinued: false,
    isNotAvailable: false,
    showDiscount: false,
    rating: 4.8,
    ratingCount: 502,
    ratingUrl:
      'https://ru.iherb.com/pr/Kirkman-Labs-Biofilm-Defense-60-Capsules/91050#product-detail-reviews',
    reviewUrl:
      'https://ru.iherb.com/r/Kirkman-Labs-Biofilm-Defense-60-Capsules/91050',
    isShippingSaver: false,
    isFeaturedBrand: false,
    productFlags: null,
    showGroupMessage: false,
    isProductCompared: false,
    isSeasonallyUnavailable: false,
    discountPercentage: null,
    salesDiscountPercentage: 0.0,
    brandCode: 'KIM',
    primaryImageIndex: 18,
    specialDealInfo: null,
    hasRating: true,
    hasTag: false,
    currencySymbol: '₽',
    isCurrencySymbolOnLeft: true,
    discountPriceValue: '3894.41',
    discountMessage: null,
    isComingSoon: false,
    discountType: 0,
    ratingStarsMap: [1.0, 1.0, 1.0, 1.0, 0.75],
  },
  {
    productId: '476',
    displayName:
      'Now Foods, комплекс буферизованного витамина C-1000, 180 таблеток',
    url: 'https://ru.iherb.com/pr/Now-Foods-Buffered-C-1000-Complex-180-Tablets/476',
    partNumber: 'NOW-00702',
    listPrice: '₽1,263.20',
    discountPrice: '₽1,263.20',
    tag: null,
    isOutOfStock: false,
    hidePrice: false,
    isDiscontinued: false,
    isNotAvailable: false,
    showDiscount: false,
    rating: 4.7,
    ratingCount: 738,
    ratingUrl:
      'https://ru.iherb.com/pr/Now-Foods-Buffered-C-1000-Complex-180-Tablets/476#product-detail-reviews',
    reviewUrl:
      'https://ru.iherb.com/r/Now-Foods-Buffered-C-1000-Complex-180-Tablets/476',
    isShippingSaver: false,
    isFeaturedBrand: false,
    productFlags: null,
    showGroupMessage: false,
    isProductCompared: false,
    isSeasonallyUnavailable: false,
    discountPercentage: null,
    salesDiscountPercentage: 0.0,
    brandCode: 'NOW',
    primaryImageIndex: 18,
    specialDealInfo: null,
    hasRating: true,
    hasTag: false,
    currencySymbol: '₽',
    isCurrencySymbolOnLeft: true,
    discountPriceValue: '1263.20',
    discountMessage: null,
    isComingSoon: false,
    discountType: 0,
    ratingStarsMap: [1.0, 1.0, 1.0, 1.0, 0.75],
  },
]
